name: Deploy Collector

on:
  workflow_dispatch:
    inputs:
      deploy_collector:
        description: 'Deploy Collector Lambda'
        type: boolean
        default: true
        required: true
      deploy_collector_schedule:
        description: 'Deploy Collector EventBridge schedule'
        type: boolean
        default: true
        required: true

jobs:
  deploy-collector:
    if: ${{ github.event.inputs.deploy_collector == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy Lambda function
        run: bash src/collect/deploy_lambda.sh

  deploy-collector-schedule:
    if: ${{ github.event.inputs.deploy_collector_schedule == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy EventBridge schedule
        run: bash src/collect/deploy_eventbridge.sh
