name: Deploy Processor

on:
  workflow_dispatch:
    inputs:
      deploy_processor:
        description: 'Deploy Processor Lambda'
        type: boolean
        default: true
        required: true
      deploy_processor_history:
        description: 'Deploy Processor History Glue Job'
        type: boolean
        default: true
        required: true

jobs:
  deploy-processor:
    if: ${{ github.event.inputs.deploy_processor == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy Lambda function
        run: bash src/process/deploy_lambda.sh

  deploy-processor-history:
    if: ${{ github.event.inputs.deploy_processor_history == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy Glue Job
        run: bash src/process_history/deploy_glue.sh